### PR TITLE
[WIP] Init NOTICE file

### PR DESCRIPTION
**Pull request by kleinech**
Init NOTICE file
- Add third party libraries excel sheet

#### Short Description
TODO:
- [ ] Add Notice head text
- [x] Add copyright holders

### CODE REVIEW

**Comment by saatkamp** [comment]
copyright 2016-2017 Karoline Saatkamp
copyright 2016-2017 Michael Falkenthal
copyright 2017 Michael Wurster

**Comment by nyuuyn** [comment]
Being mentioned in the notices for a single commit: [yay!](https://github.com/OpenTOSCA/ui/commits?author=nyuuyn)

**Comment by miwurster** [comment]
@kleinech What tasks are left to finalize this PR?

**Comment by koppor** [comment]
I think, these are good steps to move forward:

1. The UI team (AFAIK @miwurster @fakepk)  reviews whether the stated are OK as good start.
2. The UI team merges the PR
3. The UI team replaces `// TODO` by appropriate information. Example is stated at https://www.eclipse.org/projects/handbook/#legaldoc-notice
4. The UI team updates the NOTICE file with the most recent library versions.

In parallel @kleinech can state what he meant by "excel sheet". Did we create here one? Can this be added as separate PR? I spell out "separate PR" to keep things moving in this PR.

**Comment by miwurster** [comment]
Added a minimal header text for the notice file.

**Pull request merged**
